services:
  postgres:
    image: postgres:16-alpine
    container_name: gallogo-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: gallogo
      POSTGRES_PASSWORD: gallogo
      POSTGRES_DB: gallogo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
